"use client";

import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, CalendarDays, ChevronDown, Clock3, MapPin, Menu, Phone, ShieldCheck, Sparkles, X } from "lucide-react";
import { useState } from "react";

const services = [
  ["01", "Keep me healthy", "Exams, hygiene, preventive care, and family visits.", "Family & preventive"],
  ["02", "Fix a problem", "Restorative options for a tooth that needs attention now.", "Restorative care"],
  ["03", "Replace what’s missing", "Explore implants, bridges, dentures, and a clear plan.", "Implant care"],
  ["04", "Refine my smile", "Cosmetic options that protect the character of your smile.", "Cosmetic care"],
];
const faqs = [["Are you accepting new patients?", "We welcome new-patient appointment requests. Book online or call and our team will help find the right visit type."],["Can I book online?", "Yes. If you need help choosing a visit, call the office for a human recommendation."],["Do you take my insurance?", "Coverage and network participation vary by plan. Bring your insurance details so the team can explain the process before care begins."],["What if I have tooth pain?", "For urgent dental concerns, call the office first. Severe swelling, uncontrolled bleeding, trouble breathing, or a medical emergency requires emergency care."]];

export default function Home(){
  const [menuOpen,setMenuOpen]=useState(false),[openFaq,setOpenFaq]=useState<number|null>(0),[bookingOpen,setBookingOpen]=useState(false);
  const logo=<img src="/ideal-smiles-logo.png" alt="Ideal Smiles Dental — We’re dedicated to your health"/>;
  return <main className="overflow-x-hidden bg-white text-[#12365e]">
    <div className="utility"><span>Modern, thoughtful dentistry in Staten Island</span><a href="tel:+17182277400"><Phone size={13}/> Call the office</a></div>
    <header className="site-header"><a className="brand logo-brand" href="#top">{logo}</a><nav className="desktop-nav" aria-label="Primary"><a href="#care">Care</a><a href="#about">What to expect</a><a href="#patients">New patients</a><a href="#resources">Resources</a></nav><div className="header-actions"><a className="emergency-link" href="#emergency">Dental emergency</a><button className="button button-dark" onClick={()=>setBookingOpen(true)}>Book a visit <ArrowRight size={16}/></button><button className="menu-button" aria-label="Open menu" onClick={()=>setMenuOpen(true)}><Menu/></button></div></header>
    <AnimatePresence>{menuOpen&&<motion.div className="mobile-menu" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><button aria-label="Close menu" onClick={()=>setMenuOpen(false)}><X/></button><a href="#care" onClick={()=>setMenuOpen(false)}>Care</a><a href="#about" onClick={()=>setMenuOpen(false)}>What to expect</a><a href="#patients" onClick={()=>setMenuOpen(false)}>New patients</a><a href="#emergency" onClick={()=>setMenuOpen(false)}>Dental emergency</a><button className="button button-light" onClick={()=>{setMenuOpen(false);setBookingOpen(true)}}>Book a visit</button></motion.div>}</AnimatePresence>
    <section id="top" className="hero section-wrap"><div className="hero-copy"><motion.p className="eyebrow" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}>DENTISTRY FOR YOUR WHOLE FAMILY</motion.p><motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}}>Modern dentistry.<br/><i>Thoughtful care.</i></motion.h1><motion.p className="hero-text" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}}>Clear guidance, careful treatment, and a smile that still feels like your own.</motion.p><motion.div className="hero-ctas" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}}><button className="button button-dark" onClick={()=>setBookingOpen(true)}>Book your visit <ArrowRight size={17}/></button><a className="text-link" href="#care">Explore care <ArrowRight size={16}/></a></motion.div><div className="hero-meta"><span><MapPin size={17}/> 2955 Veterans Rd. W, Staten Island</span><span><Clock3 size={17}/> Hours to be confirmed</span></div></div><div className="hero-art"><img src="/hero-dental.png" alt="Dentist speaking with a smiling patient in a bright treatment room"/><div className="hero-note"><Sparkles size={16}/><span>Care that starts<br/>with listening.</span></div></div></section>
    <section id="care" className="care-section section-wrap"><div className="section-intro"><p className="eyebrow">CARE, ORGANIZED AROUND YOU</p><h2>What brings you in?</h2><p>Start with your goal. We’ll help you understand the options and the next practical step.</p></div><div className="service-grid">{services.map(([no,title,copy,tag],i)=><motion.a key={no} href="#booking" onClick={e=>{e.preventDefault();setBookingOpen(true)}} className="service-card" initial={{opacity:0,y:15}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}}><span>{no}</span><div><p className="service-tag">{tag}</p><h3>{title}</h3><p>{copy}</p></div><ArrowRight className="service-arrow" size={20}/></motion.a>)}</div></section>
    <section id="emergency" className="emergency"><div className="section-wrap emergency-inner"><div><p className="eyebrow">NEED HELP NOW?</p><h2>Tooth pain can’t wait.<br/><i>Clear help starts here.</i></h2></div><div className="emergency-copy"><p>If you have an urgent dental concern, call the office for guidance. For a life-threatening emergency, call 911 or go to the nearest emergency room.</p><a href="tel:+17182277400" className="button button-light"><Phone size={17}/> Call the office</a></div></div></section>
    <section id="about" className="approach section-wrap"><div className="visit-card"><p className="eyebrow">WHAT TO EXPECT</p><h3>A visit built around your questions.</h3>{[["01","Start with a conversation","Tell us what brings you in and what you hope to change."],["02","Understand your options","We explain practical choices, timing, and next steps clearly."],["03","Leave with a plan","You will know what happens next and who to call with questions."]].map(([n,t,c])=><div key={n}><span>{n}</span><p><b>{t}</b><small>{c}</small></p></div>)}</div><div className="approach-copy"><p className="eyebrow">A FRIENDLY, INFORMED EXPERIENCE</p><h2>Feel confident about your care.</h2><p className="lead">Whether you are coming in for a routine visit, a smile concern, or an urgent problem, our role is to make the process clearer—not more complicated.</p><div className="principles"><div><span>01</span><h3>Questions welcomed</h3><p>We make room for the concerns behind the appointment.</p></div><div><span>02</span><h3>Options explained</h3><p>Understand your care in plain language before you decide.</p></div><div><span>03</span><h3>Support beyond the chair</h3><p>Scheduling, insurance, and next steps are easier to navigate.</p></div></div></div></section>
    <section className="trust section-wrap"><div className="trust-title"><p className="eyebrow">DETAILS THAT BUILD CONFIDENCE</p><h2>Everything you need<br/>to feel prepared.</h2><p>Helpful answers before your visit can make care feel a lot less daunting.</p></div><div className="trust-list"><div><ShieldCheck/><h3>Insurance guidance</h3><p>Bring your plan details and our team can help explain the process before treatment.</p></div><div><CalendarDays/><h3>New-patient support</h3><p>Know what to bring, how to book, and what to expect when you arrive.</p></div><div><Sparkles/><h3>Modern treatment options</h3><p>Learn how today’s tools can support a more efficient, comfortable visit.</p></div></div></section>
    <section className="proof-band"><div className="section-wrap proof-grid"><div className="testimonial"><p className="eyebrow">PATIENT-FOCUSED, ALWAYS</p><blockquote>“I felt listened to from the moment I walked in. Every step was explained, and I left knowing exactly what came next.”</blockquote><small>Testimonial content to be replaced with an approved patient review.</small></div><div className="proof-actions"><h3>Have a question before you book?</h3><p>Start with the information that helps you choose the right next step.</p><a href="#resources" className="text-link">Read common questions <ArrowRight size={16}/></a><a href="#patients" className="text-link">Plan your first visit <ArrowRight size={16}/></a></div></div></section>
    <section id="patients" className="patients"><div className="section-wrap patients-inner"><div><p className="eyebrow">NEW TO IDEAL SMILES?</p><h2>Your first visit should bring clarity, not pressure.</h2><p>We’ll help you prepare for your appointment, understand the process, and know who to contact with questions.</p><button className="button button-dark" onClick={()=>setBookingOpen(true)}>Plan your first visit <ArrowRight size={17}/></button></div><ol>{[["01","Choose your visit","Book online or call for help selecting the right appointment."],["02","Tell us what you need","Share only the practical details needed to guide your visit."],["03","Arrive feeling prepared","Bring your ID, insurance information, and any questions you have."]].map(([n,t,c])=><li key={n}><strong>{n}</strong><span><b>{t}</b><small>{c}</small></span></li>)}</ol></div></section>
    <section id="resources" className="resources section-wrap"><div className="section-intro"><p className="eyebrow">HELPFUL, NOT OVERWHELMING</p><h2>Answers before your visit.</h2></div><div className="faq-list">{faqs.map(([q,a],i)=><div className="faq" key={q}><button onClick={()=>setOpenFaq(openFaq===i?null:i)} aria-expanded={openFaq===i}><span>{q}</span><ChevronDown className={openFaq===i?"rotate":""}/></button><AnimatePresence>{openFaq===i&&<motion.p initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}>{a}</motion.p>}</AnimatePresence></div>)}</div></section>
    <section className="closing section-wrap"><div><p className="eyebrow">READY WHEN YOU ARE</p><h2>Let’s make the next step simple.</h2></div><button className="button button-light" onClick={()=>setBookingOpen(true)}>Book a visit <ArrowRight size={17}/></button></section>
    <footer><div className="section-wrap footer-grid"><a className="brand logo-brand footer-brand" href="#top">{logo}</a><div><b>Visit</b><p>2955 Veterans Rd. W<br/>Suite 2G<br/>Staten Island, NY 10309</p><a href="https://maps.google.com/?q=2955+Veterans+Rd+W+Staten+Island+NY+10309">Get directions</a></div><div><b>Connect</b><p><a href="tel:+17182277400">(718) 227-7400</a><br/><span>Office hours pending confirmation</span></p><a href="#emergency">Dental emergency</a></div><div><b>Patient resources</b><p><a href="#patients">New patients</a><br/><a href="#resources">Insurance & financing</a><br/><a href="#resources">Accessibility</a></p></div></div><div className="section-wrap legal"><span>© 2026 Ideal Smiles Dental</span><span>Privacy · Notice of Privacy Practices · Terms</span></div></footer>
    <AnimatePresence>{bookingOpen&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="booking-modal" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} exit={{opacity:0,y:25}} role="dialog" aria-modal="true"><button className="modal-close" aria-label="Close booking" onClick={()=>setBookingOpen(false)}><X/></button><p className="eyebrow">REQUEST A VISIT</p><h2>Start with the right appointment.</h2><p>Online scheduling will be available here after the practice confirms its booking partner. For immediate help, call the office.</p><a className="button button-dark" href="tel:+17182277400"><Phone size={17}/> Call (718) 227-7400</a><small>This request flow is not for medical emergencies or sharing sensitive health information.</small></motion.div></motion.div>}</AnimatePresence>
  </main>
}
